const fs = require('fs');
const path = require('path');

// Base project directory (resolved dynamically relative to script location)
const projectRoot = path.resolve(__dirname, '..');

// Characters and their respective exact directories relative to project root
const characterDirs = {
    gale: 'assets/Elemental/gale/PNG',
    homura: 'assets/Elemental/homura/png/fire_knight',
    sylvan: 'assets/Elemental/sylvan/animations/PNG',
    terra: 'assets/Elemental/terra/png'
};

// Map subdirectory names to standard animation keys used in Fighter.js
const FOLDER_MAP = {
    'idle': 'idle', '01_idle': 'idle',
    'run': 'run', '02_run': 'run',
    'jump': 'jump', '03_jump': 'jump',
    'jump_up': 'jump_up', '03_jump_up': 'jump_up', 'j_up': 'jump_up',
    'jump_down': 'jump_down', '03_jump_down': 'jump_down', 'j_down': 'jump_down',
    'roll': 'roll', '04_roll': 'roll',
    '1_atk': 'attack_1', '05_1_atk': 'attack_1',
    '2_atk': 'attack_2', '06_2_atk': 'attack_2',
    '3_atk': 'attack_3', '07_3_atk': 'attack_3',
    'sp_atk': 'special', '08_sp_atk': 'special',
    'defend': 'defend', '09_defend': 'defend',
    'take_hit': 'hurt', '10_take_hit': 'hurt',
    'death': 'death', '11_death': 'death',
    'air_atk': 'air_attack'
};

const manifest = {};

// Helper to extract frame number from filename (e.g. idle_12.png -> 12)
const getFrameNumber = (filename) => {
    const match = filename.match(/(\d+)\.png$/i);
    return match ? parseInt(match[1], 10) : 0;
};

console.log('--- STARTING MANIFEST GENERATION ---');

Object.entries(characterDirs).forEach(([charKey, relPath]) => {
    const fullPath = path.join(projectRoot, relPath);
    console.log(`Scanning [${charKey}] at: ${fullPath}`);

    if (!fs.existsSync(fullPath)) {
        console.error(`ERROR: Directory not found for ${charKey}: ${fullPath}`);
        return;
    }

    manifest[charKey] = {};

    // Read all subdirectories in the character folder
    const subdirs = fs.readdirSync(fullPath).filter(file => {
        return fs.statSync(path.join(fullPath, file)).isDirectory();
    });

    subdirs.forEach(subdir => {
        const animKey = FOLDER_MAP[subdir];
        if (!animKey) {
            console.log(`Skipping unrecognized folder: ${subdir}`);
            return;
        }

        const subdirPath = path.join(fullPath, subdir);
        // Get all PNG files in this folder
        const pngFiles = fs.readdirSync(subdirPath).filter(file => {
            return fs.statSync(path.join(subdirPath, file)).isFile() && file.toLowerCase().endsWith('.png');
        });

        if (pngFiles.length === 0) {
            console.warn(`Warning: No PNG files found in ${subdirPath}`);
            return;
        }

        // Sort frames numerically (e.g. run_1, run_2, ..., run_10)
        pngFiles.sort((a, b) => getFrameNumber(a) - getFrameNumber(b));

        // Map to relative paths from project root, with forward slashes for URL compatibility
        const framePaths = pngFiles.map(file => {
            const relFramePath = path.relative(projectRoot, path.join(subdirPath, file));
            return relFramePath.replace(/\\/g, '/');
        });

        // Store in manifest
        manifest[charKey][animKey] = framePaths;
        console.log(`  ✓ Loaded [${animKey}] from [${subdir}] (${framePaths.length} frames detected and sorted)`);
    });
});

// Output manifest file as ES6 module
const outputPath = path.join(projectRoot, 'assets/Elemental/manifest.js');
const manifestContent = `// Automatically generated by scripts/generate_manifest.js
// Do not edit this file manually.

export const manifest = ${JSON.stringify(manifest, null, 4)};
`;

fs.writeFileSync(outputPath, manifestContent);
console.log(`\nSUCCESS: Manifest written to ${outputPath}`);
